export const ESTADOS_CONVERSA = {
  // Estados iniciais
  NOVO: 'NOVO',
  MENU_PRINCIPAL: 'MENU_PRINCIPAL',
  
  // Cadastro
  AGUARDANDO_NOME: 'AGUARDANDO_NOME',
  AGUARDANDO_CPF: 'AGUARDANDO_CPF',
  AGUARDANDO_EMAIL: 'AGUARDANDO_EMAIL',
  
  // Agendamento
  AGUARDANDO_DATA_AGENDAMENTO: 'AGUARDANDO_DATA_AGENDAMENTO',
  AGUARDANDO_HORARIO_AGENDAMENTO: 'AGUARDANDO_HORARIO_AGENDAMENTO',
  AGUARDANDO_CONFIRMACAO_AGENDAMENTO: 'AGUARDANDO_CONFIRMACAO_AGENDAMENTO',
  
  // Reagendamento
  ESCOLHENDO_CONSULTA_REAGENDAR: 'ESCOLHENDO_CONSULTA_REAGENDAR',
  AGUARDANDO_DATA_REAGENDAMENTO: 'AGUARDANDO_DATA_REAGENDAMENTO',
  AGUARDANDO_HORARIO_REAGENDAMENTO: 'AGUARDANDO_HORARIO_REAGENDAMENTO',
  
  // Cancelamento
  ESCOLHENDO_CONSULTA_CANCELAR: 'ESCOLHENDO_CONSULTA_CANCELAR',
  AGUARDANDO_CONFIRMACAO_CANCELAMENTO: 'AGUARDANDO_CONFIRMACAO_CANCELAMENTO',
  
  // Handoff
  ATENDIMENTO_HUMANO: 'ATENDIMENTO_HUMANO',
  
  // Lembrete
  AGUARDANDO_CONFIRMACAO_LEMBRETE: 'AGUARDANDO_CONFIRMACAO_LEMBRETE',
} as const;

export type EstadoConversa = typeof ESTADOS_CONVERSA[keyof typeof ESTADOS_CONVERSA];
